#----------------------------------------------------------------------------
#
# Arm64 CPU system registers tools
# Copyright (c) 2023, Thierry Lelegard
# BSD-2-Clause license, see the LICENSE file.
#
# Makefile for kernel top-level directory.
#
#----------------------------------------------------------------------------

.PHONY: default clean
default:
	@true
clean:
	rm -rf downloads
